### PR TITLE
Update node.js http server

### PR DESCRIPTION
**Pull request by arusakov**
Refactoring code to more node.js-like way:
- use new Buffer with fill() instead of Array with join (Buffer.alloc for Node.js v6)
- parseInt() with radix

I haven't run benchmarks yet, but this changes can have some impact on perfomance.

### CODE REVIEW

**Comment by 1st1** [comment]
These changes will likely have zero impact -- Buffer vs Array is irrelevant since it's only done once.

**Comment by arusakov** [comment]
@1st1
But response.end(...) is invoked at every request. And to respond with buffer is faster than to respond with string.

**Comment by 1st1** [comment]
@arusakov Oh, right, it should be. Let's try.

**Comment by elprans** [comment]
I didn't find much difference in Node's performance with this merged:

screenshot_20160505_130330

**Comment by arusakov** [comment]
@elprans
What about HTTP results?

**Comment by elprans** [comment]
>  What about HTTP results? 

Right.  This helped a little for 10kib responses, and, to a lesser extent, with 100kib responses, but the overall picture is largely the same.

screenshot_20160505_135354

**Comment by arusakov** [comment]
@elprans @1st1 
Thanks a lot. We made the benchmark more accurate, and this is important!

**Pull request merged**
